name: Markdown Lint

on:
  pull_request:
    paths:
      - "**/*.md"

# Set permissions to minimum required
permissions: {}

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Markdown Linter
        uses: avto-dev/markdown-lint@v1
        with:
          args: "./**/*.md"
