name: Markdown Quality
on:
  pull_request:
    paths:
      - '**/*.md'

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint Markdown
        uses: docker://avtodev/markdown-lint:v1
        with:
          args: '--config .markdownlint.json --ignore node_modules --fix'

      - name: Commit fixes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'docs: auto-format markdown files'
          file_pattern: '*.md'
