name: Code Formatting
on: [pull_request]

jobs:
  format-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check formatting
        run: pnpm format:check

      - name: Fix formatting
        if: ${{ failure() }}
        run: pnpm format:write
        continue-on-error: true

      - uses: stefanzweifel/git-auto-commit-action@v5
        if: ${{ failure() }}
        with:
          commit_message: "style: auto-format code"
          file_pattern: "*.ts *.tsx *.js *.json *.css *.md"
