name: Code Quality Gate
on:
  push:
    branches: [main]
  pull_request:
    paths:
      - "**/*.{ts,tsx}"
      - "!**/*.spec.ts"

permissions:
  contents: read

jobs:
  quality:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm exec eslint . --ext .ts,.tsx --max-warnings=0

      - name: Typecheck
        run: pnpm exec tsc --noEmit

      - name: Build
        run: pnpm exec next build --turbo
