name: Stale Management
on:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 45
          days-before-close: 14
          stale-issue-label: "stale"
          exempt-issue-labels: "pinned,security,good first issue"
          stale-issue-message: |
            This issue has been automatically marked as stale because it hasn't been updated in 45 days.
            Please update or it will be closed in 14 days.
