name: Stale Management
on:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 45
          days-before-close: 14
          stale-issue-label: "stale"
          exempt-issue-labels: "pinned,security,good first issue,documentation,bug"
          stale-issue-message: "This issue has been automatically marked as stale. Please update within 14 days to keep it open."
          close-issue-message: "Closed due to 14 days of inactivity after being marked stale."
          stale-pr-message: "This PR has been marked stale. Please resolve review comments or update within 14 days."
          operations-per-run: 100
